"""
Interactive support agent — type ANY message, get an instant grounded reply.

Purely local: embeddings via Ollama (mxbai-embed-large), replies retrieved from
real Uber_Support history (RAG), escalation decided by explainable rules.

This is a live demo of the SAME agent pipeline that run_eval.py evaluates on the
160-example golden set. The reply is NOT generated by an LLM — it is the real
Uber reply that resolved the most similar historical request (zero hallucination).

Usage:
    python interact.py
"""

import json
import sys
import io
import numpy as np

import ui

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from run_eval import Agent, RAG, keyword_intent

SAMPLE_QUESTIONS = [
    "I was charged twice for the same trip",
    "My driver was rude and honked at me the whole ride",
    "I left my wallet in the uber, how can I get it back?",
    "Someone is trying to hack my account right now",
    "My uber eats order arrived missing 2 items",
    "I got a $150 cleaning fee but there was no mess",
    "My driver was so rude and yelled at me"
]

with open("data/uber_pairs.json") as f:
    pairs = json.load(f)
rng = np.random.RandomState(7)
sample_pairs = rng.choice(len(pairs), 2000, replace=False)
anchors = {}
for idx in sample_pairs:
    intent = keyword_intent(pairs[idx]["customer_text"])
    anchors.setdefault(intent, []).append(pairs[idx]["customer_text"][:150])
anchors = {k: v[:25] for k, v in anchors.items()}

print("Loading agent (embeddings only, ~30s)...")
rag = RAG()
agent = Agent(anchors, rag)

ui.banner("Uber_Support AI Assistant (powered by real Uber replies)")
ui.kv_pairs(
    {
        "1) Intent": "classify the customer message",
        "2) Reply": "draft a grounded reply (retrieved, never generated)",
        "3) Escalation": "auto-handle vs human, with reason",
    }
)

print("\nTry one of these (or type your own, or 'quit'):")
for i, q in enumerate(SAMPLE_QUESTIONS, 1):
    print(f"    {i}. {q}")

while True:
    msg = input("\n> ").strip()
    if not msg:
        continue
    if msg.lower() in ("quit", "exit", "q"):
        ui.status("ok", "Bye! This was the same agent pipeline run_eval.py evaluates on 160 golden examples.")
        break
    if msg.isdigit() and 1 <= int(msg) <= len(SAMPLE_QUESTIONS):
        num = int(msg)
        msg = SAMPLE_QUESTIONS[num - 1]
        print(f"   (using sample {num}: {msg}...)")

    ui.hsep("-")
    print(f"  CUSTOMER: {msg[:200]}")
    ui.hsep("-")

    p = agent.process(msg)
    if p.get("out_of_scope"):
        print(f"\n  INTENT    ->  {p['intent']}")
        print(f"  ESCALATE  ->  YES  (ROUTED TO ADMIN / HUMAN - {p.get('out_of_scope_brand')} is not an Uber service)")
        print(f"      Reason: {p['escalation_reason']}")
        print(f"  RAG REPLY ->  NONE (not generated - outside Uber's scope)")
        print(f"  ACTION    ->  {p['reply']}")
    else:
        esc_txt = "YES  (human agent needed)" if p["escalate"] else "NO   (auto-handled)"
        print(f"\n  INTENT    ->  {p['intent']}")
        print(f"  ESCALATE  ->  {esc_txt}")
        if p["escalate"]:
            print(f"      Reason: {p['escalation_reason']}")
        print(f"  REPLY     ->  {p['reply']}")
        print(f"  GROUNDING ->  {p['reply_source_sim']:.2f} similarity to the real past customer message (higher = closer match)")