"""
Interactive support agent — type ANY message, get an instant grounded reply.

Purely local: embeddings via Ollama (mxbai-embed-large), replies retrieved from
real Uber_Support history (RAG), escalation decided by explainable rules.

This is a live demo of the SAME agent pipeline that run_eval.py evaluates on the
160-example golden set. The reply is NOT generated by an LLM — it is the real
Uber reply that resolved the most similar historical request (zero hallucination).

Usage:
    python interact.py
"""

import json
import sys
import io
import numpy as np

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from run_eval import Agent, RAG, keyword_intent

SAMPLE_QUESTIONS = [
    "I was charged twice for the same trip",
    "My driver was rude and honked at me the whole ride",
    "I left my wallet in the uber, how can I get it back?",
    "Someone is trying to hack my account right now",
    "My uber eats order arrived missing 2 items",
    "I got a $150 cleaning fee but there was no mess",
    "My driver was so rude and yelled at me"
]

with open("data/uber_pairs.json") as f:
    pairs = json.load(f)
rng = np.random.RandomState(7)
sample_pairs = rng.choice(len(pairs), 2000, replace=False)
anchors = {}
for idx in sample_pairs:
    intent = keyword_intent(pairs[idx]["customer_text"])
    anchors.setdefault(intent, []).append(pairs[idx]["customer_text"][:150])
anchors = {k: v[:25] for k, v in anchors.items()}

print("Loading agent (embeddings only, ~30s)...")
rag = RAG()
agent = Agent(anchors, rag)

print("=" * 64)
print("  Uber_Support AI Assistant  (powered by real Uber replies)")
print("=" * 64)
print("Type ANY customer message below and the agent will:")
print("  1) classify its intent    2) draft a grounded reply")
print("  3) decide auto-handle vs human escalation (with reason)")
print()
print("Try one of these (or type your own, or 'quit'):")
for i, q in enumerate(SAMPLE_QUESTIONS, 1):
    print(f"    {i}. {q}")
print()

while True:
    msg = input("\n> ").strip()
    if not msg:
        continue
    if msg.lower() in ("quit", "exit", "q"):
        print("\nBye! This was the same agent pipeline run_eval.py evaluates on 160 golden examples.")
        break
    if msg.isdigit() and 1 <= int(msg) <= len(SAMPLE_QUESTIONS):
        num = int(msg)
        msg = SAMPLE_QUESTIONS[num - 1]
        print(f"   (using sample {num}: {msg}...)")

    print("\n" + "-" * 64)
    print(f"  CUSTOMER: {msg[:200]}")
    print("-" * 64)

    p = agent.process(msg)
    print(f"\n  {chr(8226)} INTENT    ->  {p['intent']}")
    print(f"  {chr(8226)} ESCALATE  ->  {'YES  (human agent needed)' if p['escalate'] else 'NO   (auto-handled)'}")
    if p["escalate"]:
        print(f"      Reason: {p['escalation_reason']}")
    print(f"  {chr(8226)} REPLY     ->  {p['reply']}")
    print(f"  {chr(8226)} GROUNDING ->  {p['reply_source_sim']:.2f} similarity to the real past customer message (higher = closer match)")