import json, sys, io
from collections import Counter

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

with open("golden_set/uber_golden_draft.json", encoding="utf-8") as f:
    items = json.load(f)

# Explicit index -> (intent, escalate, reason). All 160 indices must be present.
LABELS = {
    0: ("driver_behavior", False, "Driver ended trip early and demanded cash"),
    1: ("general_inquiry", False, "Following up on a DM"),
    2: ("trip_fare_billing", False, "Unauthorized payment hold on rides not requested"),
    3: ("service_feedback", False, "Complaint about unresolved support"),
    4: ("account_access", False, "Recovering account on new device"),
    5: ("service_feedback", False, "Broad frustration with experience"),
    6: ("account_access", False, "Cannot access account"),
    7: ("uber_eats_order", False, "Money taken but food never delivered"),
    8: ("service_feedback", False, "Complaint about support handling question"),
    9: ("safety_concern", True, "Vehicle hit by uber driver - accident/legal"),
    10: ("account_access", False, "Unsolicited verification texts - account concern"),
    11: ("account_access", False, "Repeatedly asked to fill account reset form"),
    12: ("trip_fare_billing", False, "Ride passes sold out - purchase issue"),
    13: ("trip_fare_billing", False, "Disputed cleaning fee charge"),
    14: ("trip_fare_billing", False, "Charged three times for one ride"),
    15: ("trip_cancellation", False, "Driver cancelled, customer wants to complain"),
    16: ("general_inquiry", False, "Emailed promo not received"),
    17: ("lost_item", False, "Charged $15 to retrieve lost item"),
    18: ("app_technical", False, "Issue has no matching option in app form"),
    19: ("driver_behavior", False, "Driver claims car was left wet - dispute"),
    20: ("driver_behavior", False, "Driver got lost then charged tolls"),
    21: ("uber_eats_order", False, "Food late, cold, items missing"),
    22: ("trip_cancellation", False, "Driver wants customer to cancel to avoid charge"),
    23: ("general_inquiry", False, "Confirms payment method in conversation"),
    24: ("safety_concern", True, "Safety is paramount - India safety complaint"),
    25: ("app_technical", False, "Tipping system broken"),
    26: ("trip_fare_billing", False, "Extra $8 in fees, generic support response"),
    27: ("app_technical", False, "App showing an error"),
    28: ("service_feedback", False, "Complaint about long waiting times"),
    29: ("general_inquiry", False, "Message contains only a link"),
    30: ("uber_eats_order", False, "Refund for delivery fee not accepted"),
    31: ("service_feedback", False, "Frustration - no response"),
    32: ("lost_item", False, "Wife left phone in uber, driver denies"),
    33: ("app_technical", False, "App freezes when cancelling ride"),
    34: ("account_access", False, "Account disabled, wants reactivation"),
    35: ("general_inquiry", False, "MasterCard promo not working"),
    36: ("account_access", False, "Outstanding balance after reinstall - account check"),
    37: ("trip_fare_billing", False, "Final fare much higher than estimate"),
    38: ("trip_cancellation", False, "Charged extra though driver never arrived"),
    39: ("trip_cancellation", False, "Cancellation fee disputed - driver far away"),
    40: ("uber_eats_order", False, "Order messed up for second time"),
    41: ("general_inquiry", False, "Asking for discount code"),
    42: ("app_technical", False, "Carpool option missing in app"),
    43: ("lost_item", True, "Wants phone back, support provided misleading info"),
    44: ("general_inquiry", False, "How to DM customer support"),
    45: ("general_inquiry", False, "Already sent info, waiting"),
    46: ("uber_eats_order", False, "Accused of dishonesty when reporting food damage"),
    47: ("general_inquiry", False, "Asking about monthly cab service"),
    48: ("app_technical", False, "Share cab algorithm poor"),
    49: ("service_feedback", False, "Frustrated with customer care team"),
    50: ("safety_concern", True, "Self-driving car hit a person"),
    51: ("driver_behavior", False, "Driver blocking bike lane"),
    52: ("service_feedback", False, "Repeated bad experience, switching competitor"),
    53: ("account_access", False, "Cannot create account on phone or web"),
    54: ("app_technical", False, "Map location wrong near lake"),
    55: ("general_inquiry", False, "Wait time too long"),
    56: ("general_inquiry", False, "Asking for update"),
    57: ("trip_fare_billing", False, "Cannot generate invoices in MX - expense issue"),
    58: ("general_inquiry", False, "Sharing email in conversation"),
    59: ("uber_eats_order", False, "Tired of wrong orders"),
    60: ("service_feedback", False, "Positive - issue fixed via twitter"),
    61: ("general_inquiry", False, "Sent DM with phone number"),
    62: ("uber_eats_order", False, "Complaint against driver who won't deliver food"),
    63: ("trip_cancellation", False, "Driver cancelled, charged $5 fee"),
    64: ("driver_behavior", False, "Driver urinated in car, only $5 credit offered"),
    65: ("driver_behavior", False, "Car confirmed arrived but someone else in it"),
    66: ("trip_fare_billing", True, "Unauthorized charges and minor transported - urgent"),
    67: ("service_feedback", False, "Will stop using Uber"),
    68: ("trip_fare_billing", False, "Conversion error charged in USD not pesos"),
    69: ("trip_fare_billing", True, "Debit card cloned, fraudulent taxi charges"),
    70: ("general_inquiry", False, "Contacting support hub impossible remotely"),
    71: ("uber_eats_order", False, "Hung up on - order problem unresolved"),
    72: ("account_access", False, "Remove vehicle from account"),
    73: ("service_feedback", False, "Support team of no help"),
    74: ("general_inquiry", False, "Replied hours ago, waiting"),
    75: ("service_feedback", False, "Issue unresolved, what's the deal"),
    76: ("service_feedback", False, "Canned responses, issue falsely resolved"),
    77: ("general_inquiry", False, "Customer care number in Bangalore"),
    78: ("trip_cancellation", False, "Drivers accept rides 12min out, charged $5 on cancel"),
    79: ("trip_cancellation", False, "Cancelled trip still appearing as due"),
    80: ("general_inquiry", False, "Still no fix - follow up"),
    81: ("uber_eats_order", False, "Wrong order, cannot resolve in app"),
    82: ("account_access", False, "Unlock account, 2 weeks overdue"),
    83: ("general_inquiry", False, "Check direct messages"),
    84: ("account_access", False, "Cannot sign in, auth code to lost phone"),
    85: ("trip_fare_billing", False, "Cleaning fee charged without evidence"),
    86: ("general_inquiry", False, "Short confirmation"),
    87: ("general_inquiry", False, "No reply yet"),
    88: ("trip_cancellation", False, "Driver cancelled and was rude on phone"),
    89: ("trip_fare_billing", False, "Driver demanded and took more than fare"),
    90: ("account_access", False, "Cannot log into app, passwords reset"),
    91: ("trip_fare_billing", False, "Charged for ride not involved in"),
    92: ("trip_cancellation", False, "Three rides cancelled in a row"),
    93: ("general_inquiry", False, "Signup promo code not received"),
    94: ("account_access", True, "Someone trying to hack account"),
    95: ("account_access", False, "Account deactivated after cancelling a ride"),
    96: ("general_inquiry", False, "Service removed from area"),
    97: ("general_inquiry", False, "Asking if PDF receipt available"),
    98: ("uber_eats_order", False, "Reimburse uber eats meal"),
    99: ("uber_eats_order", False, "Money taken without food delivery"),
    100: ("trip_cancellation", False, "Driver turned around, charged 5 for cancel"),
    101: ("account_access", False, "Instant pay locked"),
    102: ("trip_cancellation", False, "Two cabs cancelled 5 mins away"),
    103: ("general_inquiry", False, "Eats coverage area expansion request"),
    104: ("account_access", False, "Phone change broke account"),
    105: ("driver_behavior", False, "Driver screwed up 3x, app support stinks"),
    106: ("general_inquiry", False, "Question about promo code amounts"),
    107: ("account_access", False, "Random text from uber, not using app"),
    108: ("service_feedback", False, "Automated responses, no real people"),
    109: ("general_inquiry", False, "Confirming sent report"),
    110: ("service_feedback", False, "Report conversation one message only"),
    111: ("trip_fare_billing", False, "Two overcharge issues, one unresolved"),
    112: ("trip_cancellation", False, "Charged $5 when driver cancels"),
    113: ("general_inquiry", False, "Uber credit card application status"),
    114: ("account_access", True, "Unresolved refund; customer explicitly requests a human agent"),
    115: ("uber_eats_order", False, "Issue with McDonald's driver"),
    116: ("app_technical", False, "Link not working, avoid slow support"),
    117: ("account_access", False, "Reset account help"),
    118: ("driver_behavior", False, "Driver put customer out of car en route"),
    119: ("trip_cancellation", False, "Driver cancelled, charged $5.15"),
    120: ("uber_eats_order", False, "Food order problem reported as scam"),
    121: ("uber_eats_order", False, "Bug contacting eats driver, starving"),
    122: ("driver_behavior", False, "Driver taking long route"),
    123: ("account_access", False, "Update mobile number after moving countries"),
    124: ("service_feedback", False, "Standard support request; routine resolution pattern available"),
    125: ("trip_cancellation", False, "Drivers cancel 5 min after accept, charged each time"),
    126: ("driver_behavior", False, "Driver disrespectful to women"),
    127: ("trip_fare_billing", True, "Charged $157 with fake evidence, never picked up"),
    128: ("general_inquiry", False, "Thank you"),
    129: ("general_inquiry", False, "When will Eats be in Delaware"),
    130: ("trip_fare_billing", False, "Refund for ride while drunk"),
    131: ("account_access", False, "Drivers license approval to drive"),
    132: ("uber_eats_order", False, "Driver said no place to leave food, lives in house"),
    133: ("trip_cancellation", False, "Stranded at motorway junction, driver issues"),
    134: ("account_access", False, "Changed phone, number not working"),
    135: ("driver_behavior", False, "Driver screwed up 3x, service stinks"),
    136: ("general_inquiry", False, "Promo code amount question"),
    137: ("account_access", False, "Random text, suspect account issue"),
    138: ("service_feedback", False, "Automated responses, no real people"),
    139: ("general_inquiry", False, "Confirming report sent"),
    140: ("service_feedback", False, "Runaround from support"),
    141: ("trip_fare_billing", False, "Overcharge issues, one unresolved"),
    142: ("trip_cancellation", False, "Charged $5 if driver cancels"),
    143: ("general_inquiry", False, "Credit card application status"),
    144: ("account_access", True, "Unauthorized verification codes, cannot access account"),
    145: ("uber_eats_order", False, "McDonald's driver issue"),
    146: ("app_technical", False, "Link not working, don't route to slow support"),
    147: ("account_access", False, "Reset account help"),
    148: ("driver_behavior", False, "Driver put customer out mid-trip"),
    149: ("trip_cancellation", False, "Driver cancelled, charged cancellation fee"),
    150: ("uber_eats_order", False, "Food order problem reported as scam"),
    151: ("uber_eats_order", False, "Bug contacting eats driver"),
    152: ("driver_behavior", False, "Driver took long route"),
    153: ("account_access", False, "Change mobile number for new country"),
    154: ("safety_concern", True, "Scared for life, driver wouldn't unlock door"),
    155: ("trip_cancellation", False, "Drivers cancel after accept, charged each time"),
    156: ("driver_behavior", False, "Driver disrespectful to women"),
    157: ("trip_fare_billing", True, "Charged $157 with fake evidence, never picked up"),
    158: ("general_inquiry", False, "Thank you"),
    159: ("general_inquiry", False, "When will Eats be in Delaware"),
}

missing = [i for i in range(len(items)) if i not in LABELS]
if missing:
    raise SystemExit(f"MISSING labels for indices: {missing}")

for i, item in enumerate(items):
    intent, escalate, reason = LABELS[i]
    item["intent"] = intent
    item["escalation"] = escalate
    item["escalation_reason"] = reason

with open("golden_set/uber_golden.json", "w", encoding="utf-8") as f:
    json.dump(items, f, ensure_ascii=False, indent=2)

intents = Counter(i["intent"] for i in items)
esc = sum(1 for i in items if i["escalation"])
print(f"Golden set: {len(items)} hand-labeled examples")
print(f"Escalation: {esc}/{len(items)} = {esc/len(items):.1%}")
print("\nIntent distribution:")
for k, v in intents.most_common():
    print(f"  {k}: {v}")